# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vVS9XMqgqhWVbKOOGyQZrcwm9Vv7RuCm
"""

import rasterio

##rasterio

import earthpy
from rasterio.plot import show

import os
from glob import glob
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import earthpy as et
import earthpy.spatial as es
import earthpy.plot as ep

image = rasterio.open('/test_images/subset_0_of_LT05_L1TP_180032_20060727_20180311_01_T1_reprojected.tif')

red = image.read(3)
nir = image.read(4)

ndvi = es.normalized_diff(nir, red)

titles = ["Landsat 5 - Normalized Difference Vegetation Index (NDVI)"]

# Turn off bytescale scaling due to float values for NDVI
ep.plot_bands(ndvi, cmap="gray", cols=1, title=titles)
plt.show()

meta = image.profile
meta.update(driver='GTiff')
meta.update(count= 1)

with rasterio.open('NDVI.tif', 'w', **meta) as file:
      file.write(ndvi, 1)
      file.close()